/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PlayerInterface extends ethers.utils.Interface {
  functions: {
    "addDevice(address)": FunctionFragment;
    "deviceToPlayer(address)": FunctionFragment;
    "devices(address,address)": FunctionFragment;
    "initializePlayer(string,address)": FunctionFragment;
    "isInitialized(address)": FunctionFragment;
    "name(address)": FunctionFragment;
    "removeDevice(address)": FunctionFragment;
    "setUsername(string)": FunctionFragment;
    "usernameToAddress(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addDevice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deviceToPlayer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "devices",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePlayer",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "name", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeDevice",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setUsername", values: [string]): string;
  encodeFunctionData(
    functionFragment: "usernameToAddress",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "addDevice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deviceToPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializePlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usernameToAddress",
    data: BytesLike
  ): Result;

  events: {
    "DeviceAdded(address,address)": EventFragment;
    "DeviceRemoved(address,address)": EventFragment;
    "PlayerInitialized(address,string)": EventFragment;
    "UserNameChanged(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeviceAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeviceRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PlayerInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserNameChanged"): EventFragment;
}

export type DeviceAddedEvent = TypedEvent<
  [string, string] & { device: string; player: string }
>;

export type DeviceRemovedEvent = TypedEvent<
  [string, string] & { device: string; player: string }
>;

export type PlayerInitializedEvent = TypedEvent<
  [string, string] & { player: string; username: string }
>;

export type UserNameChangedEvent = TypedEvent<
  [string, string] & { player: string; username: string }
>;

export class Player extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PlayerInterface;

  functions: {
    addDevice(
      addr: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deviceToPlayer(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    devices(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initializePlayer(
      _name: string,
      device: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isInitialized(
      player: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    name(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    removeDevice(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUsername(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    usernameToAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addDevice(
    addr: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deviceToPlayer(arg0: string, overrides?: CallOverrides): Promise<string>;

  devices(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initializePlayer(
    _name: string,
    device: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isInitialized(player: string, overrides?: CallOverrides): Promise<boolean>;

  name(arg0: string, overrides?: CallOverrides): Promise<string>;

  removeDevice(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUsername(
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  usernameToAddress(arg0: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addDevice(addr: string, overrides?: CallOverrides): Promise<boolean>;

    deviceToPlayer(arg0: string, overrides?: CallOverrides): Promise<string>;

    devices(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initializePlayer(
      _name: string,
      device: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isInitialized(player: string, overrides?: CallOverrides): Promise<boolean>;

    name(arg0: string, overrides?: CallOverrides): Promise<string>;

    removeDevice(addr: string, overrides?: CallOverrides): Promise<boolean>;

    setUsername(_name: string, overrides?: CallOverrides): Promise<boolean>;

    usernameToAddress(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "DeviceAdded(address,address)"(
      device?: string | null,
      player?: string | null
    ): TypedEventFilter<[string, string], { device: string; player: string }>;

    DeviceAdded(
      device?: string | null,
      player?: string | null
    ): TypedEventFilter<[string, string], { device: string; player: string }>;

    "DeviceRemoved(address,address)"(
      device?: string | null,
      player?: string | null
    ): TypedEventFilter<[string, string], { device: string; player: string }>;

    DeviceRemoved(
      device?: string | null,
      player?: string | null
    ): TypedEventFilter<[string, string], { device: string; player: string }>;

    "PlayerInitialized(address,string)"(
      player?: string | null,
      username?: null
    ): TypedEventFilter<[string, string], { player: string; username: string }>;

    PlayerInitialized(
      player?: string | null,
      username?: null
    ): TypedEventFilter<[string, string], { player: string; username: string }>;

    "UserNameChanged(address,string)"(
      player?: string | null,
      username?: null
    ): TypedEventFilter<[string, string], { player: string; username: string }>;

    UserNameChanged(
      player?: string | null,
      username?: null
    ): TypedEventFilter<[string, string], { player: string; username: string }>;
  };

  estimateGas: {
    addDevice(
      addr: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deviceToPlayer(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    devices(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializePlayer(
      _name: string,
      device: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isInitialized(
      player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    removeDevice(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUsername(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    usernameToAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addDevice(
      addr: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deviceToPlayer(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    devices(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializePlayer(
      _name: string,
      device: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isInitialized(
      player: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeDevice(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUsername(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    usernameToAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
